### ISSUE TITLE
Which version should I use

### ISSUE THREAD

**Issue by zuzuviewer** [victoriafrench/react-native-dialogbox#34]
My RN version is 0.39.2.Which react-native-dialogbox's version should I pick?

**Comment by deavial** [comment]
Hi @zuzuviewer the current release works with 0.39.2, npm will complain with a warning that peer dependency of RN 0.41.2 is missing. You can ignore it. The component doesn't have a native bridges and will work fine on RN 0.30+

**Comment by zuzuviewer** [comment]
Thank you very much @victoriafrench
