### ISSUE TITLE
Render Issue: Calling Pop with Multiple Buttons 

### ISSUE THREAD

**Issue by gregberns** [victoriafrench/react-native-dialogbox#36]
It looks like the PopContent component was built to handle more than 2 buttons, but when rendering they do not display well. 

I'd like to display 4 options for a user to select from. 'confirm()' allows OK and Cancel, horizontally aligned. I'd like to supply 'pop()' with 3-4 buttons to select from that are vertically stacked on each other.

I have a feeling that the issue is with styling and I'll take a look at what might be screwed up. If you have any thoughts let me know though.
![screenshot_2017-03-15-11-32-48](https://cloud.githubusercontent.com/assets/1767458/23965061/0162bae4-0974-11e7-98db-9cd041c72373.png)

```
handleOnPress = () => {
     this.dialogbox.pop({
          title: 'Title',
          content: 'Content',
          btns: [
               {
                    text: 'OK',
                    callback: () => {
                         this.dialogbox.close();
                         //ok && typeof ok.callback === 'function' && ok.callback();
                    },
               },
               {
                    text: 'Cancel',
                    callback: () => {
                         this.dialogbox.close();
                         //cancel && typeof cancel.callback === 'function' && cancel.callback();
                    },
               },		
               {
                     text: 'Action 3',
                     callback: () => {
                          this.dialogbox.close();
		     },
               },
               {
                     text: 'Another Action',
                     callback: () => {
                           this.dialogbox.close();
                     },
               },
           ],
     });
}
```

**Comment by deavial** [comment]
This is definitely an issue. I am currently traveling (spring break). I will fix this as soon as I can get setup somewhere.

**Comment by gregberns** [comment]
Thanks! I just put in RP #37 that helps resolve the issue.
Great little project by the way. So glad you put in 'pop()' so I could supply the custom object my self.

**Comment by deavial** [comment]
I think this new version will work out for you.
