### ISSUE TITLE
Put it a bit higher?

### ISSUE THREAD

**Issue by andrisole92** [victoriafrench/react-native-dialogbox#56]
Is it possible to make it appear a little bit higher?

**Comment by deavial** [comment]
Yes, all styles can be overridden. This is the default style for the box in this example:

```jsx
<DialogBox style={{
     tipBoxView: {
          backgroundColor: '#fff',
	  justifyContent: 'center',
	  alignItems: 'center',
	  width: Dimensions.get('window').width - 50,
	  borderRadius: 12,
	  overflow: 'hidden',
     }
}} />
```
So to move it up you could add a `marginTop` and give it a negative value.
