### ISSUE TITLE
is it possible to modify position of dialog box?

### ISSUE THREAD

**Issue by Harryki** [victoriafrench/react-native-dialogbox#62]
![dialog box](https://user-images.githubusercontent.com/9028406/32530694-72d679e6-c3f4-11e7-9fdb-406cc82f9114.png)

Since my <DialogBox /> component is nested inside the page, it doesn't overlay the headers and don't get position at the center. 

`<DialogBox style={{ position: 'absolute', right: 0, top: 0 }} />` seemed not working

**Comment by deavial** [comment]
Hi @Harryki 

In the current version, the `style` property breaks convention and has children. The `popupContainer`, `overlay`, and `tipBoxView` is what you would most likely be interested in styling. [Defaults here](https://github.com/victoriafrench/react-native-dialogbox/blob/master/lib/styles.js)

For example, to change the layout of the white `tipBoxView` you may do something like this:

```js
<DialogBox style={{ tipBoxView: { backgroundColor: 'yellow' } }} />
```

However, in React Native, `position: absolute` will only render you absolute **within the bounds of the component's parent**. So if the dialog is declared inside a view it will only be absolute within that view. The dialog would need to be declared at the root of your app and you would either need to bubble up an event to show it or use something like redux to control the display. It doesn't work the way HTML would treat an absolute positioned element.

**Comment by Harryki** [comment]
Awesome! Thanks for the reply
