### ISSUE TITLE
Specifying height to the dialog box

### ISSUE THREAD

**Issue by anurag060** [victoriafrench/react-native-dialogbox#68]
I am using this.dialogbox.confirm({...}). If the content is more, the dialog box is going beyond the screen height and the buttons are not visible at all. Is there a way to give specific height to the dialog box.

**Comment by deavial** [comment]
Yes, you can.

```js
const myStyleOverrides = {
     tipBoxView: {
          height: 200
     },
};

<DialogBox style={myStyleOverrides} />
```
